### ISSUE TITLE
Question for eval_BreastPathQ_SSL.py line 123.

### ISSUE THREAD

**Issue by hust-linyi** [srinidhiPY/SSL_CR_Histo#5]
Hi, thanks for sharing the code! Amazing work!

In eval_BreastPathQ_SSL.py line 123, https://github.com/srinidhiPY/SSL_CR_Histo/blob/adc301ec74b69defc51cfe2ab3effccc7c1f60c5/eval_BreastPathQ_SSL.py#L123

`target = target.long()
`
It could translate the float tensor into int64, thus the val_loss could be wrong. Is this a bug here?

Thanks

**Comment by srinidhiPY** [comment]
Hi, Really sorry for the late reply.

I looked at the issue in line 123, and it's an unintentional bug over here. It should have been the target.float() (as in Line 55) instead of target.long() data type. Since the pretrained model is made available you could use these scripts to fine-tune the model again. Let me know if you face any issues. Thanks
