### ISSUE TITLE
BreastPathQ: After trianing the model by WSIs, the result which evaluated by Task-specific supervised fine-tuning is bad

### ISSUE THREAD

**Issue by xiaozhu0816** [srinidhiPY/SSL_CR_Histo#7]
- For BreastPathQ, when I used the pretrian model author released and did the finetune, I could get a similar result to your paper.

- But I tried to pretrain the model myself, following the instructions (1. Self-supervised pretext task: Resolution sequence prediction (RSP) in WSIs). I used the best pretrain model and did the same things as before. After finetuning, the result was not good enough like paper.

- paper:<img width="848" alt="image" src="https://user-images.githubusercontent.com/72501744/192129127-48496486-edf8-4a6e-a180-975e4aea5e1e.png">

- my reslut:     <img width="725" alt="image" src="https://user-images.githubusercontent.com/72501744/192129132-9028df2d-758f-42dd-855a-180e17b24c02.png">

- During my training,  4 WSIs which are bad wsis cannot be used. But I don’t think it is an essential problem for me, because just lose hundreds of data.

**Comment by srinidhiPY** [comment]
I am really sorry for the late reply.

In our experiments for BreastPathQ, we have used *69 WSI’s* of the training
set for pretraining the self-supervised model. I think the issue in your
case may be because of 4 WSIs, which were not used.

As the number of patches that can be extracted from a given WSI
mainly depends on the tissue content, there might be a high probability
that you have lost some significant amount of data for SSL training.
