### ISSUE TITLE
How to use the pre-trained models?

### ISSUE THREAD

**Issue by HHHedo** [srinidhiPY/SSL_CR_Histo#8]
Hi， 
Thank you for your great work!
I wonder how to use your model for linear probing.
I empirically find the results are not promising when I use your released models with the MLP  removed.
If the MLP can not be removed, then how to use the model with only one magnitude of pathological images?
Looking forward to  your help! Thanks again.

**Comment by srinidhiPY** [comment]
Hi,

Our motivation to use MLP was primarily inspired by SimCLR paper "A Simple Framework for Contrastive Learning of Visual Representations". We empirically found a MLP is more beneficial rather than a simple linear layer on all three histopathology tasks and also with end-to-end finetuning of pretrained model. 

Hope that helps.

**Comment by HHHedo** [comment]
> Hi,
> 
> Our motivation to use MLP was primarily inspired by SimCLR paper "A Simple Framework for Contrastive Learning of Visual Representations". We empirically found a MLP is more beneficial rather than a simple linear layer on all three histopathology tasks and also with end-to-end finetuning of pretrained model.
> 
> Hope that helps.

Thanks for your help!
Since I did not find the results of the SSL feature quality assessment (e.g., linear probing) in your MedIA paper. 
Is it reasonable for the following up researches to use your model for linear probing  1) with the MLP removed. 2) concatenation of the features of the same patch with the MLP kept.

**Comment by srinidhiPY** [comment]
Sure you can try that settings. Hope it might help.
